version: 2.1
jobs:
  build:
    # machine:
    #   image: ubuntu-2004:202010-01
    macos: # executor type
      xcode: "13.2.1"
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      
      - run: flutter doctor
    #   - run: flutter analyze
    #   - run: flutter test
    #   - run: flutter -v build apk
      - when:
          condition:
            not: 
              equal: [ XXXflutter-circlci, << pipeline.git.branch >> ]
          steps:
            - run: echo "Not CircleCI << pipeline.git.branch >>"
            - run: flutter analyze
      - when:
          condition:
            equal: [ flutter-circleci, << pipeline.git.branch >> ]
          steps:
            - run: echo << pipeline.git.branch >>
            - run: flutter test

# https://stackoverflow.com/questions/50789578/how-can-the-code-coverage-data-from-flutter-tests-be-displayed